#file: noinspection undefined
spring:
  application:
    name: greeting-service
greeting-service:
  greeting: oie
  default-value: Mondo
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
